### ISSUE TITLE
problem with inserting in woody snippet

### ISSUE THREAD

**Issue by samboy59** [GravityPDF/gravity-pdf#1178]
Hello
My Engilsh is not good ,Sorry.
When I add this code in woody snippet 
this happend:

Don't Panic

The code snippet you are trying to save produced a fatal error on line 2:
Uncaught Error: Class 'GFPDFHelperFieldsField_Form' not found in /home/subdomain/website/wp-content/plugins/insert-php/admin/metaboxes/base-options.php(846) : eval()'d code:2 Stack trace: #0 /home/frajabza/website/wp-content/plugins/insert-php/admin/metaboxes/base-options.php(846): eval() #1 /home/frajabza/website/wp-content/plugins/insert-php/admin/metaboxes/base-options.php(983): WINP_BaseOptionsMetaBox->validateCode('// Gravity PDF ...', 'php') #2 /home/frajabza/website/wp-content/plugins/insert-php/libs/factory/metaboxes/includes/form-metabox.class.php(105): WINP_BaseOptionsMetaBox->afterSavingForm(17401) #3 /home/frajabza/website/wp-content/plugins/insert-php/libs/factory/metaboxes/metabox.class.php(211): Wbcr_FactoryMetaboxes409_FormMetabox->save(17401) #4 /home/frajabza/website/wp-content/plugins/insert-php/libs/factory/metaboxes/metaboxes.php(167): Wbcr_FactoryMetaboxes409_Metabox->actionSavePost(17401) #5 /home/frajabza/website/wp-includes/class-wp-hook.php(289): Wbc

The previous version of the snippet is unchanged, and the rest of this site should be functioning normally as before.

Please use the back button in your browser to return to the previous page and try to fix the code error. If you prefer, you can close this page and discard the changes you just made. No changes will be made to this site.

**How can I solve that**

**Comment by samboy59** [comment]
I write it in wrong palce
