### ISSUE TITLE
Enhanced Media Library conflict with Gravity PDF

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#433]
User reported the following error when trying to activate Gravity PDF on their Subdomain Multisite install:

```
Fatal error: Uncaught Error: Call to undefined function wp_terms_checklist() in /var/www/vhosts/marianilandscape.com/httpdocs/wp-content/plugins/enhanced-media-library/enhanced-media-library.php:396 Stack trace: #0 /var/www/vhosts/marianilandscape.com/httpdocs/wp-includes/plugin.php(525): wpuxss_eml_enqueue_media('') #1 /var/www/vhosts/marianilandscape.com/httpdocs/wp-includes/media.php(3503): do_action('wp_enqueue_medi...') #2 /var/www/vhosts/marianilandscape.com/httpdocs/wp-content/plugins/gravity-forms-pdf-extended/src/bootstrap.php(516): wp_enqueue_media() #3 /var/www/vhosts/marianilandscape.com/httpdocs/wp-includes/plugin.php(525): GFPDF\Router->load_assets('') #4 /var/www/vhosts/marianilandscape.com/httpdocs/wp-settings.php(393): do_action('init') #5 /var/www/vhosts/marianilandscape.com/httpdocs/wp-config.php(99): require_once('/var/www/vhosts...') #6 /var/www/vhosts/marianilandscape.com/httpdocs/wp-load.php(37): require_once('/var/www/vhosts...') #7 /var/www/vhosts/marianilandscape.com/httpdocs/wp-admin/admin.php(3 in /var/www/vhosts/marianilandscape.com/httpdocs/wp-content/plugins/enhanced-media-library/enhanced-media-library.php on line 396
```

**Comment by jakejackson1** [comment]
Tried to replicate the issue but couldn't. The error shows it's nothing to do with Gravity PDF though.

**Comment by jakejackson1** [comment]
Was able to replicate this issue. Reopening to investigate further.

**Comment by jakejackson1** [comment]
After reviewing, this issue stems from our enqueuing of scripts and styles too early (on the `init` action). To correct this we're changing to `admin_enqueue_scripts` which WordPress docs recommend: https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/
