### ISSUE TITLE
Check for WP_Error before handling Confirmations. 

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#999]
```
Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/swiercs.nl/httpdocs/wp-content/plugins/gravity-forms-pdf-extended/src/model/Model_Shortcodes.php:255
Stack trace:
#0 /var/www/vhosts/swiercs.nl/httpdocs/wp-includes/class-wp-hook.php(288): GFPDF\\Model\\Model_Shortcodes->gravitypdf_confirmation('<div id='gform_...', Array, Object(WP_Error))
#1 /var/www/vhosts/swiercs.nl/httpdocs/wp-includes/plugin.php(208): WP_Hook->apply_filters('<div id='gform_...', Array)
#2 /var/www/vhosts/swiercs.nl/httpdocs/wp-content/plugins/gravityforms/gravityforms.php(5458): apply_filters('gform_confirmat...', '<div id='gform_...', Array, Object(WP_Error), false, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
#3 /var/www/vhosts/swiercs.nl/httpdocs/wp-content/plugins/gravityforms/form_display.php(1567): gf_apply_filters('gform_confirmat...', '<div id='gform_...', Array, Object(WP_Error), false)
#4 /var/www/vhosts/swiercs.nl/httpdocs/wp-content/plugins/gf-mollie-by-indigo/class-g...
'
```

**Comment by jakejackson1** [comment]
@ayenmot we need to add guarded checks (IF statements) against [WP_Error](https://developer.wordpress.org/reference/classes/wp_error/) in the following methods:

https://github.com/GravityPDF/gravity-pdf/blob/development/src/Helper/Helper_Abstract_Pdf_Shortcode.php#L167
https://github.com/GravityPDF/gravity-pdf/blob/development/src/Helper/Helper_Abstract_Pdf_Shortcode.php#L186
https://github.com/GravityPDF/gravity-pdf/blob/development/src/Helper/Helper_Abstract_Pdf_Shortcode.php#L338

See https://code.tutsplus.com/tutorials/wordpress-error-handling-with-wp_error-class-i--cms-21120 for details on how WP_Error works

**Comment by jakejackson1** [comment]
Looks like this needs some more work: https://github.com/GravityPDF/gravity-pdf/commit/a3a4739feaf8f76379ff4ec39e560a0aafe5c75a

User has let me know `$entry` is actually got the `WP_Error`. We should just make sure all the variables passed into the function aren't a `WP_Error` (e.g. `$form` and `$entry1`)
